version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: beerapp-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: beerdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - beerdata:/var/lib/postgresql/data

volumes:
  beerdata: