spring:
  application:
    name: BeerProj

  datasource:
    url: jdbc:postgresql://localhost:5432/beerdb
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/changelog/changelog.yml

springdoc:
  swagger-ui:
    path: "/swagger"
    url: "/v3/api-docs"
    configUrl: "/v3/api-docs/swagger-config"

beer-application:
  urls:
    employee: http://localhost:8081