version: "3.8"

name: beerstack

services:
  postgres:
    image: postgres:15
    container_name: beer-postgres

  mongo:
    image: mongo:7.0
    container_name: beer-mongo

  redis:
    image: redis:7.2
    container_name: beer-redis
    command: ["redis-server", "--appendonly", "yes"]

  service-employee:
    build: ../service-employee
    image: beer/employee:dev
    container_name: beer-employee
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports: ["8081:8081"]
    depends_on: [mongo, redis]

  service-main:
    build: ../service-main
    image: beer/main:dev
    container_name: beer-main
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports: ["8080:8080"]
    depends_on: [postgres, service-employee]

networks:
  default:
    name: beer-net

volumes:
  pg-data:
  mongo-data:
  redis-data:
