name: CI service-main
on:
  push:
    paths: ["service-main/**", ".github/workflows/ci-service-main.yml"]
  pull_request:
    paths: ["service-main/**"]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: service-main
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v3

      - name: Normalize EOL (gradlew)
        run: sed -i 's/\r$//' gradlew

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build --no-daemon
        # если сейчас нужно «зеленеть» — временно:
        # run: ./gradlew clean build -x test --no-daemon
