name: CI service-employee
on:
  push:
    paths: ["service-employee/**", ".github/workflows/ci-service-employee.yml"]
  pull_request:
    paths: ["service-employee/**"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - run: |
          cd service-employee
          ./gradlew test build --no-daemon